[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "5tWvUdpE4wkTAff4FvcVQZdG8e1m2FqaWSaRPd7vSUMg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabetheidelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

my-custom-script = "echo 'My new script is dope!'"